config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: %w[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: %w[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path, alert: 'Must be logged in to perform that action' unless logged_in?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %w[show edit update destroy]
  before_action :require_user, except: %w[show index]
  before_action :require_same_user, only: %w[edit update destroy]

  def show; end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article, notice: 'Article was created successfully.'
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was updated successfully'
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    redirect_to @article, alert: 'Can only edit or delete your own articles' if current_user != @article.user &&
                                                                                !current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %w[show edit update]
  before_action :require_admin, except: %w[index show]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), notice: 'Catgory name was successfully updated'
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    redirect_to categories_path, alert: 'Only admins can perform that action' unless logged_in? && current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_session = params[:session]
    user = User.find_by(email: user_session[:email].downcase)
    if user&.authenticate(user_session[:password])
      session[:user_id] = user.id
      redirect_to user, notice:  'Logged in successfully'
    else
      flash.now[:alert] = 'There was something wrong with log in details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %w[show edit update destroy]
  before_action :require_user, only: %w[edit update]
  before_action :require_same_user, only: %w[edit update destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path, notice: "Welcome #{@user.username}, you have successfully logged ."
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "#{@user.username} was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to articles_path, notice: 'Account and all associated articles successfully deleted'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    redirect_to @user, alert: 'Can only edit or delete your own profile' if current_user != @user &&
                                                                            !current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class='row justify-content-md-center'>
    <div class='col-8 mt-4'>
      <div class='card text-center shadow mb-5 bg-white rounded'>
        <div class='card-header font-italic'>
          <%= link_to article.user.username, user_path(article.user) unless article.user.nil? %>
        </div>
        <div class='card-body'>
          <h5 class='card-title'><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
          <p class='card-text'><%= truncate(article.description, length: 50) %></p>
          <% if article.categories.any? %>
            <div class='mb-3'>Categories: <%= render article.categories %></div>
          <% end %>
          <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
            <%= link_to 'Delete', article_path(article), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you Sure?' } %>
          <% end %>
        </div>
        <div class='card-footer text-muted'>
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class='row justify-content-center'>
  <div class='col-10'>
    <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, class: 'shadow p-3 mb-5 bg-ligth rounded', local: true) do |f| %>
      <div class='form-group row'>
        <%= f.label :title, class: 'col-2 col-form-label'%>
        <div class='col-10'>
          <%= f.text_field :title, class: 'form-control shadow rounded', placeholder: 'Title of article' %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :description, class: 'col-2 col-form-label' %>
        <div class='col-10'>
          <%= f.text_area :description, rows:10, class: 'form-control shadow rounded', placeholder: 'Discription of article' %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :category, class: 'col-2 col-form-label'%>
        <div class='col-10'>
          <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: 'Please select zero or more categories' }, { multiple: true, size: 5, class: 'custom-select shadow rounded' }) %>
        </div>
      </div>
      <div class='form-group row justify-content-center'>
        <div class='col-md-3'>
          <%= f.submit class: 'btn form-control btn-outline-success btn-large' %>
        </div>
        <div class='col-md-3'>
          <%= link_to 'Cancel', articles_path, class: 'btn form-control btn-outline-info btn-large' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class='text-center mt-4'>Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class='text-center mt-4'>Postings</h1>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @Articles, :container => false %>
</div>
<%= render 'article', obj: @articles %>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @Articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class='text-center mt-4'>New article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class='text-center mt-4'><%= link_to @article.title, edit_article_path(@article), class: 'text-success' %></h2>
  <div class='row justify-content-md-center'>
    <div class='col-8 mt-4'>
      <div class='card text-center shadow mb-5 bg-white rounded'>
        <div class='card-header font-italic'>
          <%= @article.user.username %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </div>
        <div class='card-body'>
          <div class='card-text text-left'><%= simple_format(@article.description) %></div>
          <% if @article.categories.any? %>
            <div>Categories: <%= render @article.categories %></div>
          <% end %>
          <% if logged_in? && @article.user == (current_user || !current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-info' %>
            <%= link_to 'Delete', article_path(@article), class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        <div class='card-footer text-muted'>
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>&nbsp</span>

app/views/categories/_form.html.erb
<div class='row justify-content-center'>
  <div class='col-10'>
    <%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, class: 'shadow p-3 mb-5 bg-ligth rounded', local: true) do |f| %>
      <div class='form-group row'>
        <%= f.label :name, 'Category name', class: 'col-2 col-form-label'%>
        <div class='col-10'>
          <%= f.text_field :name, class: 'form-control shadow rounded', placeholder: 'Enter a name' %>
        </div>
      </div>
      <div class='form-group row justify-content-center'>
        <div class='col-md-3'>
          <%= f.submit class: 'btn form-control btn-outline-success btn-large' %>
        </div>
        <div class='col-md-3'>
          <%= link_to 'Cancel', categories_path, class: 'btn form-control btn-outline-info btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class='text-center mt-4'>Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class='text-center mt-4'>Categories</h1>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @categories, :container => false %>
</div>
<% @categories.each do |category| %>
  <div class='row justify-content-md-center'>
    <div class='col-4 mt-4'>
      <div class='card text-center shadow mb-5 bg-white rounded'>
        <div class='card-body'>
          <h5 class='card-title'><%= link_to category.name, category_path(category), class: 'text-success' %></h5>
          <div class='card-text'><%= pluralize(category.articles.count, 'article') %></div>
        </div>
        <div class='card-footer text-muted'>
          <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class='text-center mt-4'>New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class='text-center mt-4'>Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
  <div class='text-center mt-4'>
    <%= link_to 'Edit ' + @category.name, edit_category_path, class: 'btn btn-outline-info' %>
  </div>
<% end %>
<div class='flickr_pagination'>
  <%= will_paginate @category_articles, :container => false %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @category_articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class='py-4 bg-light text-black-50 sticky-footer'>
  <div class='container text-center'>
    <small>Copyright &copy;2020 Alex Blog</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class='alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show' role='alert'>
      <%= msg %>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'ALEX BLOG', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Bloggers', users_path, class: 'nav-link'%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %> 
            <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
          <% end %>
          <%= link_to 'View Articles', articles_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %> 
            <%= link_to 'New Category', new_category_path, class: 'dropdown-item' %>
          <% end %>
          <%= link_to 'View Categories', categories_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class='nav-link dropdown-toggle' href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= '(Admin)' if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View Profile', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Delete Profile', user_path(current_user), method: :delete, class: 'dropdown-item text-danger', data: { confirm: 'Are you sure?'} %>

          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, method: :delete, class: 'nav-link'%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', login_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: 'nav-link'%>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alex's Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='d-flex flex-column'>
    <div class='sticky-container'>
      <%= render 'layouts/navigation'%>
      <div class='page-body'>
        <div class='container'>
          <%= render 'layouts/messages' %> 
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<div id='page-content'>
  <div class='jumbotron text-center'>
    <h1 class='display-4'>Alex Blog</h1>
    <p class='lead'>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class='my-4'>
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up", signup_path, class: 'btn btn-success btn-lg' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='alert alert-danger alert-dismissible fade show' role='alert'>
    <h4 class='alert-heading'>The following errors prevetned the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class='row justify-content-center'>
  <div class='col-10'>
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class: 'shadow p-3 mb-5 bg-ligth rounded', local: true) do |f| %>
      <div class='form-group row'>
        <%= f.label :username, class: 'col-2 col-form-label'%>
        <div class='col-10'>
          <%= f.text_field :username, class: 'form-control shadow rounded', placeholder: 'Enter a username' %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :email, class: 'col-2 col-form-label' %>
        <div class='col-10'>
          <%= f.email_field :email, class: 'form-control shadow rounded', placeholder: 'Enter an email' %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :password, class: 'col-2 col-form-label'%>
        <div class='col-10'>
          <%= f.password_field :password, class: 'form-control shadow rounded', placeholder: 'Enter a password' %>
        </div>
      </div>
      <div class='form-group row justify-content-center'>
        <div class='col-md-3'>
          <%= f.submit(@user.new_record? ? 'Sign up' : 'Update Account', class: 'btn form-control btn-outline-success btn-large') %>
        </div>
        <div class='col-md-3'>
          <%= link_to 'Cancel', users_path, class: 'btn form-control btn-outline-info btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class='text-center mt-4'>Edit Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class='text-center mt-4'>Bloggers</h1>
<div class='flickr_pagination'>
  <%= will_paginate @users, :container => false %>
</div>
<% @users.each do |user| %>
  <div class='row justify-content-md-center'>
    <div class='col-8 mt-4'>
      <div class='card text-center shadow mb-5 bg-white rounded'>
        <div class='card-header font-italic'>
          <%= link_to user.username, user %>
        </div>
        <div class='card-body'>
          <h5 class='card-title'>
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>
          <div class='card-text mb-2'><%= pluralize(user.articles.count, 'article') %></div>
          <%= link_to 'View Profile', user, class: 'btn btn-outline-success' %>
          <% if logged_in? && user == current_user %>
            <%= link_to 'Edit Profile', edit_user_path(user), class: 'btn btn-outline-info' %>
          <% end %>
        </div>
        <div class='card-footer text-muted'>
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class='text-center mt-4'>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class='text-center mt-4'><%= @user.username %> Profile</h1>
<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>
  <div class='text-center mt-4'>
    <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-outline-info'%>
  </div>
<% end %>
<h3 class='text-center mt-4'><%= @user.username %> Articles</h3>
<div class='flickr_pagination'>
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article', obj: @articles %>
<div class='flickr_pagination mb-4'>
  <%= will_paginate @articles, :container => false %>
</div>